services:
  google-earth-topo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: google-earth-topo
    restart: unless-stopped
    environment:
      MAX_ZOOM: 17
      LOG_FILE: /data/server.log
    volumes:
      - ./data:/data
    networks:
      pidor-net:
        aliases:
          - google-earth-topo.pidor.local

  nginx:
    image: nginx:alpine
    container_name: google-earth-topo-nginx
    restart: unless-stopped
    depends_on:
      - google-earth-topo
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/nginx-cache:/var/cache/nginx
      - ./data/nginx-logs:/var/log/nginx
    networks:
      pidor-net:
        aliases:
          - google-earth-topo-nginx.pidor.local

networks:
  pidor-net:
    external: true
    name: pidor-net
